[package]
name = "yajilin-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
union-find = "0.4.2"
priority-queue = "2.0.2"
